from setuptools import setup, find_packages

setup(
    name="langchain-agents",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "langchain>=0.1.0",
        "langchain-core>=0.1.0",
        "langchain-community>=0.0.10",
        "typing-extensions>=4.5.0",
        "pydantic>=2.0.0",
        "python-dotenv>=1.0.0",
        "requests>=2.31.0",
        "aiohttp>=3.9.0",
        "tqdm>=4.66.0",
        "openai>=1.6.0",
        "chromadb>=0.4.0",
        "tiktoken>=0.5.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "tenacity>=8.2.0",
        "PyYAML>=6.0",
    ],
    python_requires=">=3.9",
    author="Your Name",
    author_email="your.email@example.com",
    description="A multi-agent framework using LangChain",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
    ],
) 